<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'GtnPersistZendDb\Service\RepositoryFactoryInterface'                                      => __DIR__ . '/src/GtnPersistZendDb/Service/RepositoryFactoryInterface.php',
  'GtnPersistZendDb\Service\ZendDbRepositoryAbstractFactory'                                 => __DIR__ . '/src/GtnPersistZendDb/Service/ZendDbRepositoryAbstractFactory.php',
  'GtnPersistZendDb\Service\ZendDbRepositoryFactory'                                         => __DIR__ . '/src/GtnPersistZendDb/Service/ZendDbRepositoryFactory.php',
  'GtnPersistZendDb\Db\Adapter\MasterSlavesAdapterFactory'                                   => __DIR__ . '/src/GtnPersistZendDb/Db/Adapter/MasterSlavesAdapterFactory.php',
  'GtnPersistZendDb\Db\Adapter\MasterSlavesAdapterInterface'                                 => __DIR__ . '/src/GtnPersistZendDb/Db/Adapter/MasterSlavesAdapterInterface.php',
  'GtnPersistZendDb\Db\Adapter\MasterSlavesAdapter'                                          => __DIR__ . '/src/GtnPersistZendDb/Db/Adapter/MasterSlavesAdapter.php',
  'GtnPersistZendDb\Exception\UnexpectedValueException'                                      => __DIR__ . '/src/GtnPersistZendDb/Exception/UnexpectedValueException.php',
  'GtnPersistZendDb\Exception\RuntimeException'                                              => __DIR__ . '/src/GtnPersistZendDb/Exception/RuntimeException.php',
  'GtnPersistZendDb\Exception\MissingConfigurationException'                                 => __DIR__ . '/src/GtnPersistZendDb/Exception/MissingConfigurationException.php',
  'GtnPersistZendDb\Exception\ExceptionInterface'                                            => __DIR__ . '/src/GtnPersistZendDb/Exception/ExceptionInterface.php',
  'GtnPersistZendDb\ZendRandomGenerator'                                                     => __DIR__ . '/src/GtnPersistZendDb/ZendRandomGenerator.php',
  'GtnPersistZendDb\RandomGeneratorInterface'                                                => __DIR__ . '/src/GtnPersistZendDb/RandomGeneratorInterface.php',
  'GtnPersistZendDb\Infrastructure\ZendDbRepository'                                         => __DIR__ . '/src/GtnPersistZendDb/Infrastructure/ZendDbRepository.php',
  'GtnPersistZendDb\Module'                                                                  => __DIR__ . '/src/GtnPersistZendDb/Module.php',
);
