<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfPersistenceZendDb\Infrastructure\ZendDbRepository'         => __DIR__ . '/src/ZfPersistenceZendDb/Infrastructure/ZendDbRepository.php',
    'ZfPersistenceZendDb\Infrastructure\ZendDbRepositoryFactory'  => __DIR__ . '/src/ZfPersistenceZendDb/Infrastructure/ZendDbRepositoryFactory.php',
    'ZfPersistenceZendDb\Module'                                  => __DIR__ . '/src/ZfPersistenceZendDb/Module.php',
    'ZfPersistenceZendDb\Db\Adapter\MasterSlavesAdapterInterface' => __DIR__ . '/src/ZfPersistenceZendDb/Db/Adapter/MasterSlavesAdapterInterface.php',
    'ZfPersistenceZendDb\Db\Adapter\MasterSlavesAdapter'          => __DIR__ . '/src/ZfPersistenceZendDb/Db/Adapter/MasterSlavesAdapter.php',
);